apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-app-of-apps
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: components/argocd_apps
    repoURL: https://github.com/tjungbauer/cluster-bootstrap-helm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
