apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/instance: mgmt-app-of-apps
    gitops.ownedBy: cluster-config
  name: set-console-banner
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: clusters/config/console-banner
    repoURL: 'https://github.com/tjungbauer/cluster-bootstrap-helm'
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true

