apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: install-advanced-cluster-security
  namespace: openshift-gitops
spec:
  destination:
    namespace: stackrox
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: advanced-cluster-security-operator/operator/overlays/latest
    repoURL: https://github.com/redhat-cop/gitops-catalog.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
