apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: install-quay-enterprise-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/management-cluster/apps/quay-enterprise
    repoURL: https://github.com/tjungbauer/cluster-bootstrap-helm
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
