{{ if .Files.Get "clusters/management-cluster/sealed-secrets/sealed-htpasswed-secret.yaml" }}
file.fs-license.conf:               {{ .Files.Get "clusters/management-cluster/sealed-secrets/sealed-htpasswed-secret.yaml" }}
{{ else }}
{{ fail "you need to supply your license file! add 'fs-license.conf' to your chart 'config' directory." }}
{{ end }}
