{{ if .Files.Get "sealed-secrets/sealed-htpasswed-secret.yaml" }}
{{ .Files.Get "sealed-secrets/sealed-htpasswed-secret.yaml" }}
{{ else }}
{{ fail "you need to supply your license file! add 'fs-license.conf' to your chart 'config' directory." }}
{{ end }}
