apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
  labels:
    gitops.ownedBy: cluster-config
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/all/apps/sealed-secrets-operator/overlays/update-status
    repoURL: https://github.com/tjungbauer/cluster-bootstrap-helm
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
