apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgDiwRO66g8mOwi+sywxc38HKtqO+gJj1D8Id6vp90KsWiB6iyiXH+BAAZM6PWfz9a8D2mV0oZ5GzKUx117La55MfLtVKsjFg2Xr7f4jTa+ZExNt91abFAezGNbz5ZWFC2hoXPm1YOxvxP+cBbAhjdIy7W9yBlVlmsOE6QH10u0KCX6G7r7yZjlvmOTYFiYg+FymNY22HU5s2TZMXW1wcB4l/RJ4fJyewZcq9XkPimQCloiQ4A/SosY6SHD0y3DzMw3u1MsLRk/bBlPDMKxY8s9pZzQmBleKN7RdAlXmkUBn/jPO3In2od19fz6US7UwlNlZ+eXaXhuuuJVbY/Xl1dR/2POrn5ADEJ44y0BTb4/p1Fvv9p7ISpyWSGhnc0dpFvOUFRDh3MSO+fpt44xoQLGrHsQNbx+X5/J02kjyqvA5C52jJYvBPFjdDMr7PtkoU7qdxhxVQg8CKPWXDR+1+JxacXSvKCj1kC/WkXSNjxJ4sjs4LP/dKo6PLe73l8l8SO8ycQmRuEZ37fKk5VOfdHUpg3PAjW5QocqzrRGdLcDt32TQ4NfPeINf3BwTy2dE60VEE4DrpBvu0cSmOdML1Hn/kZpu/UjUdfiUgakd2jjDS6DmiSVRFdJTQAiH1j75afLP1YXo3gMd5HiHkNv2k32lV4rAN/QTLjSlB21i7TLp2UQ3WcZt7hoKOVQl9p8xhYug+BlVVb2tWyP8vM51yK7FFGexx4FeLo/XkNsBhNvQDqRur4E5JUw2rRQUX6/f+xxkjyxaoLq2gXR//BPSoVAWQ6mBYwMeL5EacICRS9XK8W7FDLGkqBTcNNgofRPkrOYmPAUpzCyWK8qy3J7Hz1VDTnOjS2is0LbE5SqvGKoZF/aNBwBy53HOc4fZM31FmrkSFL0wtI5PJko7e4TOrr5Lqr9aipWoeCYhQyP0PtJ0kjfkQWUOuRb9sbhycCi1XZxqwrt7LjuI2aRMMa/gOwgyeSwiljcZeDwvoFSj/kqM3f3V6NaVfF0ouSWhY2bA4UIvmRyhLf2ZoSN8rulURNBix49oLtFF8LAMNuJ+fGM7iVbmb2z05kOkdPY7vlfJ+mZaMcAv1ZmRmd5oF+oRaUAwFIXlsJj0LVFIJUTkUuacxVjWFKZnIJEyePdjHNvULMS1e/Z1ir7Q9x2IEK4tdrIshLjMTcj2LFAbttvMchi8AWzDBLpoo8clstF8e20Vxj4i/EBd4RhgzvWNFoX/A7M+WhOgZVg4VpbNyLipYpr2+HpwG9j5D/q2AMmf1kBLodld3sQ0ZZxKxqOgp5wOlxxfYNblrP5tw2tdySd72tMYPfZp6ouXHgpbWHSZVIRWLys3n6zwohV9YFWibLTut94tQuC05CyUvcrc1l49FBG7ViI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

