apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBIGDg3ue+kDKZHBxd8Jl7Ia/OC6slorZep1E0QL4fuoy6rMsANZjTwaIGpqA9Yd9+HStjPKzTI6GWC0K/z3k+8z+PEr0eFb5wqt4AAJnQU8YDHPTnam8+XIPn1CqFX18As2UhpNOEp9fDzfPFTEIjX2DdLXWpWmqnvsZizfhBeoSbc1s47tFz5VSH4AZAc8y7K4neDDTBFBchYBIiWCkpnrPAWkhyW9qCP9teWYDplqxT70W7mfR4U1D6ciGSy6AViZ7MME8kcr0QSUFyIKCShky9r9Auh+LELOwyQzRT554jU6O0gZC6yh5WWFBl1semGwWuKRv/JOPFFrznqu6nqcTpjIgC4OJpqRs5UkY+vOR6ekGSEcJFswM+zZNhj6abo16lDPhoQJ7bOkPCOOViL4qVwxulWKCTYPvdnWJN3+5TgeFTiZ0DBL1iJBwsYwQ7nQBSdEM1C9xrRG2JvyQA0ynnPJCVFqW5KI18hIZe4cMQ7Sn45wPMmu8/dKctS1Gm+eZvu/GUqUB88dJnb33anc+4kT5SaGGgtPukLjoZ07itb68EMBhbkems72co5fwAy8hJHUgGUP800gA4xIIUrd5ESTP/t13xcarYI02bAzHIwvi9q65C4LRli74NH7X8uvKzcvqAuPBZhdSsLeedEzEsNsS+15MFv2II8buGJsU5BpM0AGeH0iBAgxtVQRhTdvglA/FgqjDVh56zpnbRMK4kiLeLIo/PtUzZPIYeRiIxX7eJfI6/gpAWw1ouHzZdi9xV+ZKRloZ3UuK/Xom57qH54FNmJjna8aTyovgeI/3Z8lWkuiKdhCnO7pAw/6kc/RhsEKHocGn8uwCDwCT6WinccZGSsjKRpkrvt/bbwzD9dTnOmOGmLsr9liM8xNLdFY+/GdSdczhtWBf1KxdKa/N0GYniMQSLzsaZ84J/DdSRsZGHcdR0Cx7jXTbplEykCO7zpjwhT5k/AIWCrgYzLcrop7q49z+h4MbwQ2xRRqfGsc272h57Nyqm2RxNnAE/w0uLyucByh+JCSPMXf2K7ga4YUGYUFg0IOnFsg+yj8toCdqQpJDHWxUHG1mL2LHogl+iW1KuQ5OxHt5aqBHS+Ss+usleAt9hwpxZgcH6s1bLi8oCG1T8UDrZkJXc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

