apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAjxD+bfTJcFKMWhWVCJFEvjI8NtNYgNnuuQE/wi0DVmhL7lntuy49AeNOJw3GIeYBfXS1vycFF6+NDbol7YJo6i2Xenebl+W+nqH1SAti5EYDxx5VxSU5ZmCv8S/fm+PxhMyOIk38ZgZD+3dSxMEac/pUoqone3LZnpDz3veW5dOaSi8Nd0qi63fWEnV97j/w21JUAyZoDnFi6Y75nYnPqDUX+aMOCuA+Amf1bRGYv7uYmsgRHeR9hLMkM7vpP6ytxW1u638XKEflmXgt5RAoJNMFWk3m8lng24URYzJETysytUJ1zt4vqayyEJN2rQuHW2WnpOrvMVhKy8LQdL0S+slhDeNnlSZN1L2Qar3kpCY7olfl25/8mFojJYGfI5EgyNpY4MrHhW/OTLXa31FEmreZAEJbtP2bc25GzVRu9xAyZpVm6r/nzXaki3xDRtDYBbUYNeeH6BmLvA8FihURIBUd0Tr5nieg3KeL6vrE8jLQL+gEVhRm72O9wPZBGn3DBmsFY5qec65cm2HTexkBTw3ziOsIC477b2cWDxoAjh+r0BPiarNTdZ4/NkkDMttxFYw1x972EfxhqTqc3ykAgJJ/x8my25aoycpwc9lRYN7yV3XUmNAKr4YT0BDwBdtGgg72DWSQ0QUqq3gHM6xCEFVnaQLiYHG4gnUufB1e/3KNKHon86eR2fNaFmcM9BqOaB1CMgPqzh9d1scxwZwr7uT/OGMmBVa7LrkT629wcnOrRptxaDewLr9xZZG5MYEvLwOHWBY/CGx+TIvA0BPd7V0TA+QRw4XEmBz2GRDL3pGwvkkx+efADRAeHVsqnFad+aqcGXzp5wqYcJ/ijtElLyLji+2u7UF/0BbvtSfErPmyXsRa81c5uzGxFJ1kCbVKShfbsjJwbRUoACSCz3dRwtxOsgdI0T5jNVPt7FEDO8/41bhEahriXmyqaa1NlaJoVyuA7yEwdy8AYgjQ1E5DRCxtrp+eGvXTVv+ZZ+IEaCB4O13UOqXvxYUeJlUCZVf/q+rtxuVMYOD21V5VgflYfwc9JRhAH7tJMMfjfUewrNt1pXbNgKjYIUDiR6dW6bUo5WzuYtPvIe6s5WZol9jdlVDrqNrCn6DXkie7gJKR8LDJ5izV7RAhEJeOo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

