apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBG9TJfqxGD4s4g8GX6+JDuhnpLLgtkCTmb8io0VcSwVSJ82XKip+ebFPzSHITS7uWRLOTIYaARvM0f5mNwgGMMOUclxLYjNvhTyl06W8KnWkqeCLoifcjRgQ5FX1H+Izj2AoxrvWftwpIfQSwcoIJf3gCgLiCl4gyaJ5rYSNOZet6LUtLpg/1H6uQ8wKbczncJd282mvwJfShjgIeV3AKRaC128VktZ/Dp2s7pzlJPLhvoJpoz3fqk2/cpfEIFIwSvOX5JkzqCGMhlUav/EdQZRPGEpyxXAHgrI/8o4Snmb0V5ezJlfn2kZ/XCo86gWx4WzcfoV9cdKWooh35Nw190mdiTlh3BxlBSfRKVzlBtoTb62BQVxqL98YR/hx0W+ZGEXMioi+Vt2qruylGfgn9YyjDC7dMVCVA44ZJiueIitRCD1r1BTcqqdb6KJUDsrdO0Du51S5N7Wyrm8Q411Pfzrlcc3PDiFb043BFqc9YT++O94bR2ovp7kaZmZct+HGnlR2uCL3wi7I+LiQJWFdLBzEWFuV6ijj62CkJqD03Fx6KA5KeXL5lpQsEamqmbeodGzDXKqKzvz21yqnVA0l2dCl2mqwfnKmNUbWIFDw+LJe7ITnaUogWbM+yjBheqs4jtPQxBfNEoFXgSvtXxhK4UehM05Xk1eth8iDmgmL4lXabtaIZLGSCEnj/doMXnyiEbPAFDQEQBeN2dakvCxAp2JTlncIC+29OyfrNBW1/a0VB5OZUGAh3P1vmX1gqzn4zC27xie2TYaIRRtrV+hPnEDdq4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

